### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by Shirobachi** [Shirobachi/friendly-octo-tribble#27]

**Comment by fisurek** [comment]
[Dokumentacja aplikacji “Friendly Octo Tribble” f68e588542b1470aa5ca4bb5d7b1e04c.md](https://github.com/Shirobachi/friendly-octo-tribble/files/8626453/Dokumentacja.aplikacji.Friendly.Octo.Tribble.f68e588542b1470aa5ca4bb5d7b1e04c.md)

**Comment by Shirobachi** [comment]
Please add it as ./README.md, read more [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)
!
